---
title: "Appendix K"
output:
  html_document: default
  pdf_document: default
---

```{r "setup", include=FALSE}
# knitr settings
require("knitr")
opts_knit$set(root.dir = "..") # set working directory to be ssj-graph-r directory
knitr::opts_chunk$set(error = TRUE)

```

```{r project_settings, echo=FALSE, include=FALSE}
# source scripts for plots and helper functions
source("scripts/helper_functions.R") # load all the helper functions
source("scripts/figures.R") # load all the functions that generate the graphs
source("scripts/tables.R") # load in the table file to calc acre-ft totals to export to csv.

# data sources
dsa_legal_data <- readRDS("data/dsa_legal/dsa_legal.rds")
dsa_etrf <- readRDS("data/dsa_etrf/dsa_etrf.rds")
delta_regions <- readRDS("data/delta_regions/delta_regions.rds")
fieldstations_data <- readRDS("data/fieldstations/wy2016/fieldstations_wy2016.rds")
fieldstations_data_2015 <- readRDS("data/fieldstations/wy2015/fieldstations_wy2015.rds")
subregions <- readRDS("data/subregions/subregions.rds")
eto <- readRDS('data/eto/eto.rds')

# vector containing the water years
water_years <- c(2015, 2016)

# footer 
footer <- paste('Updated ', Sys.Date())

# list of crops to generate
crops_2_gen <- sort(names(crops))
crops_2_gen <- crops_2_gen[!crops_2_gen %in% c("Unknown", "Sudan Grass")]


# sims does not provide data for native or urban vegetation class, so they need to be manually removed from the df
no_sims_class <- c("Eucalyptus", "Floating Vegetation", "Nursery", "Riparian","Semi-agricultural/ROW", "Upland Herbaceous", "Urban", "Water", "Wet herbaceous/sub irrigated pasture")

dsa_etrf <- dsa_etrf %>% filter(!(model=="sims" & cropname %in% no_sims_class))
dsa_legal_data <- dsa_legal_data %>% filter(!(model=="sims" & cropname %in% no_sims_class))


```

# I.1 DAILY EVAPOTRANSPIRATION RATES

```{r whisker_ETxMonths_per_crop_method, echo=FALSE, fig.width = 7, fig.height = 4}

# list of methods to use for the plots
methods_2_gen <- methods_names

# loop through the months
for(m in 1:length(methods_2_gen)){
  mod <- methods_2_gen[m]

  print(mod)
  
  # loop through all crops types
  for(i in 1:length(crops_2_gen)){

  # get the id from the crop name
  cropid <- lookup_cropid(crops_2_gen[i])
    
    # plot
    p <- whisker_ETxMonths_per_crop_method_2yrs(dsa_legal_data, 'dsa', mod, cropid)


    # add plot to rmarkdown output
    plot(p)
  }
}

```



# I.2 CUMULATIVE MONTHLY EVAPOTRANSPIRATION

```{r lineplot_cumET, echo=FALSE, fig.width = 7, fig.height = 4}

# loop through the crops
for(i in 1:length(crops_2_gen)){

  # get the id from the crop name
  cropid <- lookup_cropid(crops_2_gen[i])
  
  #plot
  p <- line_ETxMonths_cumulative(dsa_legal_data, cropid,  "dsa")
  
  # add footer
  p <- p + labs(caption=footer)
  
  plot(p)
}
```

# I.3 REFERENCE EVAPOTRANSPIRATION

```{r eto, echo=FALSE, fig.width = 7, fig.height = 4}


# add date
eto_boxplot <- function(selected_model, title){
eto_data <- eto %>% mutate(date=date_from_wy_month(wateryear, month)) %>%# add a date field by combining month and water year
  filter(model==selected_model)

# construct the plot object
p <- ggplot(eto_data, aes(x=date, ymin=p9/10, lower=p25/10, middle=median/10, upper=p75/10,  ymax=p91/10, fill=model)) + 
  scale_x_date(date_breaks="3 month", date_labels  = "%b")+
  geom_boxplot(stat="identity") +
  coord_cartesian(ylim=c(0, 8))+
  ggtitle(title) +
  ylab("ETo (mm/day)") +
  geom_vline(xintercept = as.numeric(as.Date('2015-09-15')),colour="black", linetype="dashed", size=1.25, alpha=0.5)+
  annotate("text", x=as.Date('2015-04-01') , y=8, label="2015", size=5)+
  annotate("text", x=as.Date('2016-04-01') , y=8, label="2016", size=5)+
  scale_fill_manual(labels=c(spatial_cimis_eto="Spatial CIMIS", disalexi_eto="DisALEXI", detaw_eto="DETAW"), values=c(spatial_cimis_eto="#619CFF", disalexi_eto="#00BA38", detaw_eto="#F8766D")) +
  theme_bw() +  # change theme simple with no axis or tick marks
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        plot.title = element_text(hjust = 0.5, size=16),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        legend.position="none", # position of legend or none
        legend.direction="horizontal", # orientation of legend
        legend.title= element_blank(), # no title for legend
        legend.key.size = unit(0.5, "cm"),
        axis.text.y=element_text(size=14),
        axis.text.x=element_text(size=12),
        axis.title.y=element_text(size=14),
        axis.line = element_line(color="black", size=1)
        )
  p
}

eto_boxplot("spatial_cimis_eto", "Spatial CIMIS ETo")
eto_boxplot("disalexi_eto", "DisALEXI ETo")
eto_boxplot("detaw_eto", "DETAW ETo")

```




# I.4 FRACTIONS OF REFERENCE EVAPOTRANSPIRATION

```{r etrf_ee, echo=FALSE, fig.width = 7, fig.height = 4}

# loop through the crops
for(c in crops_2_gen){
  p <- etrf2(dsa_etrf, c)

  # add plot to rmarkdown output
  plot(p)
}
```
