---
title: "SSJ-DELTA-CU Daily figures"
output:
  html_document: default
---

# Daily ET measurements

```{r "setup", include=FALSE, warning = FALSE, message=FALSE}
# knitr settings
require("knitr")
opts_knit$set(root.dir = "..") # set working directory to be ssj-graph-r directory
knitr::opts_chunk$set(error = TRUE)

```

```{r project_settings, echo=FALSE, message=FALSE, include=FALSE, warning = FALSE}
library(plotly)

# source scripts for plots and helper functions
source("scripts/helper_functions.R") # load all the helper functions
source("scripts/figures.R") # load all the functions that generate the graphs
source("scripts/tables.R") # load in the table file to calc acre-ft totals to export to csv.

# data sources
daily_grid <- readRDS("data/fieldstations/grid/fieldstation_grid_daily.rds")

# vector containing the water years
water_years <- c(2015, 2016)

# footer 
footer <- paste('Updated ', Sys.Date())

daily_grid

```

```{r exclude_outliers, echo=FALSE}
# there likey is some bad data with extreamly high/low values. Let's filter it out of the df

daily_grid <- daily_grid %>% filter(mean < 20, mean > -20)



```

```{r, echo=FALSE, message=FALSE, warning = FALSE}
# field stations measurements
# pull in the dates csv from the ssj-field-measurements-2016 repo (assumes that there is a local copy)
# the local copy should have the same directory folder as ssj-graphs-r
list_of_csvs <- list.files(path="../ssj-field-measurements-2016/daily data", pattern="D[0-9][0-9](.*?)(.csv)", full.names=TRUE)

# for loop to load in all the raw csv files to single data frame
load_csv <- function(file_list) {
  listofdfs <- list() #Create a list in which you intend to save your df's.
  for (i in 1:length(file_list)) {
    #print(file_list[i])
    g <- read.csv(file_list[i], stringsAsFactors = FALSE)
    listofdfs[[i]]<-g
  }
  df <- ldply(listofdfs, data.frame) # make into one dataframe 
}

raw_field_data <- load_csv(list_of_csvs)

# clean up station name and set model name to field
field <- raw_field_data %>% separate(stationName, into = c("Station_ID", "IslandName", "Crop"), sep='_') %>% mutate(date=as.Date(date), mean=ET_SR_aH_qc_Dgf, model="field") %>% filter(date>=as.Date('2016-05-01'), date<as.Date('2016-10-01'))

field_select <- field %>% select(Crop, Station_ID, date, mean, model)

daily_grid_w_field <- bind_rows(daily_grid, field_select)


```

```{r, echo=FALSE}




daily_et_station <- function(selected_station){
  
  overpass_dates <- as.Date(c('2016-05-2',
      '2016-05-10',
      '2016-05-18',
      '2016-05-26',
      '2016-06-3',
      '2016-06-11',
      '2016-06-19',
      '2016-06-27',
      '2016-07-5',
      '2016-07-13',
      '2016-07-21',
      '2016-07-29',
      '2016-08-6',
      '2016-08-14',
      '2016-08-22',
      '2016-08-30',
      '2016-09-7',
      '2016-09-15',
      '2016-09-23',
      '2016-10-1'))

daily_single_station <- daily_grid_w_field %>% 
  filter(Station_ID == selected_station)

crop_at_station <- daily_single_station$Crop[1]

p<-ggplot(daily_single_station, aes(x=date, y=mean, color=model))+
  geom_line(size=1.25)+
  ylab("ET mm/day")+
  geom_vline(xintercept = as.numeric(overpass_dates), linetype=2, colour="black", alpha=0.3)+
  ggtitle(paste(selected_station, toupper(crop_at_station)))+
  theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
      plot.title = element_text(hjust = 0.5, size=16),
      panel.grid.minor = element_blank(),
      legend.position="right", # position of legend or none
      legend.direction="vertical", # orientation of legend
      legend.title= element_blank(), # no title for legend
      legend.key.size = unit(0.5, "cm"),
      axis.text.y=element_text(size=14),
      axis.text.x=element_text(size=14),
      axis.title.y=element_text(size=14),
      axis.title.x=element_blank(),
      axis.line = element_line(color="black", size=1))

  m <- list(
    l = 50,
    r = 50,
    b = 50,
    t = 50,
    pad = 4
  )

 p<-ggplotly(p)%>%
  layout(autosize = F, width = 900, height = 600, margin = m)
}
```



```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D01")
p
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D02")
p
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D03")
p
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D04")
p
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D05")
p
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D07")
p
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D08")
p
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D09")
p
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D10")
p
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D11")
p
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D12")
p
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D13")
p
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
p<-daily_et_station("D14")
p
```
