---
title: "SSJ-DELTA-CU Metric figures"
output:
  html_document: default
---

```{r "setup", include=FALSE}
# knitr settings
require("knitr")
opts_knit$set(root.dir = "..") # set working directory to be ssj-graph-r directory
knitr::opts_chunk$set(error = TRUE)

```

```{r project_settings, echo=FALSE, include=FALSE}
# source scripts for plots and helper functions
source("scripts/helper_functions.R") # load all the helper functions
source("scripts/figures.R") # load all the functions that generate the graphs
source("scripts/tables.R") # load in the table file to calc acre-ft totals to export to csv.

# data sources
dsa_legal_data <- readRDS("data/dsa_legal/dsa_legal.rds")
dsa_etrf <- readRDS("data/dsa_etrf/dsa_etrf.rds")
delta_regions <- readRDS("data/delta_regions/delta_regions.rds")
fieldstations_data <- readRDS("data/fieldstations/wy2016/fieldstations_wy2016.rds")
fieldstations_data_2015 <- readRDS("data/fieldstations/wy2015/fieldstations_wy2015.rds")
subregions <- readRDS("data/subregions/subregions.rds")
eto <- readRDS('data/eto/eto.rds')

# vector containing the water years
water_years <- c(2015, 2016)

# footer 
footer <- paste('Updated ', Sys.Date())

```


```{r, fig.width = 10, fig.height = 4}
line_AFxMonths_bars<- function(data, crop_id, aoi_region){
  # creates a line plot for ET by months for a specifc crop and region
  
  # subset data by selected crop id number, region
  sub_data <- filter(data, region == aoi_region, level_2 == crop_id) %>% 
    mutate(date=date_from_wy_month(wateryear, month)) # add a date field by combining month and water year

  # look up the cropname 
  cropname <- lookup_cropname(crop_id)

  # construct the plot object
  p <- ggplot(sub_data, aes(date, crop_acft, group=model)) + 
    #geom_line(aes(linetype=model),size=1.25)+
    geom_bar(aes(fill=model), stat="identity", position="dodge")+
    geom_text(aes(label=round(mean/10, 2)), hjust=0.5)+
    scale_x_date(date_breaks="3 month", date_labels  = "%b")+
    #coord_cartesian(ylim=c(0, 9))+
    ggtitle(cropname) +
    ylab("Acre-Feet") +
    geom_vline(xintercept = as.numeric(as.Date('2015-09-16')),colour="black", linetype="dashed", size=1.25, alpha=0.5)+
    #annotate("text", x=as.Date('2015-04-01') , y=9, label="2015", size=5)+
    #annotate("text", x=as.Date('2016-04-01') , y=9, label="2016", size=5)+
    scale_fill_manual(values=model_palette, labels=methods_named_list) +
    #scale_color_manual(values=model_palette, labels=methods_named_list) +
    #scale_linetype_manual(values=model_lny)+
    theme_bw() +  # change theme simple with no axis or tick marks
    theme(panel.border = element_blank(), panel.grid.major = element_blank(),
          plot.title = element_text(hjust = 0.5, size=16),
          panel.grid.minor = element_blank(),
          axis.title.x = element_blank(),
          legend.position="bottom", # position of legend or none
          legend.direction="horizontal", # orientation of legend
          legend.title= element_blank(), # no title for legend
          legend.key.size = unit(0.5, "cm"),
          axis.text.y=element_text(size=14),
          axis.text.x=element_text(size=12),
          axis.title.y=element_text(size=14),
          axis.line = element_line(color="black", size=1)
          )
}


dsa_legal_data_metric <- dsa_legal_data %>% filter(model %in% c("itrc", "ucdmetric"))
p <- line_AFxMonths_bars(dsa_legal_data_metric, 1, 'dsa')
p

```




```{r lineplot_ET, echo=FALSE, fig.width = 7, fig.height = 4}

# list of crops to generate
#crops_2_gen <- c("Alfalfa", "Almonds", "Corn", "Pasture", "Potatoes", "Rice", "Tomatoes", "Vineyards")
crops_2_gen <- crop_list()

dsa_legal_data_metric <- dsa_legal_data %>% filter(model %in% c("itrc", "ucdmetric"))

# loop through the crops
for(i in 1:length(crops_2_gen)){
  
  # get the id from the crop name
  cropid <- lookup_cropid(crops_2_gen[i])
  
  # generate plot for the crop for the delta service area
  p <- line_AFxMonths_bars(dsa_legal_data_metric, cropid,  "dsa")
  
  # add footer with the date
  p <- p + labs(caption=footer)
  
  # add plot to rmarkdown output
  plot(p)
}
```



